// firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6f1SvmxQljip0KkGeAvbNz2wC9gCThtc',
    appId: '1:853014272041:web:02d41914790c2a056ce438',
    messagingSenderId: '853014272041',
    projectId: 'mindnest-45772',
    authDomain: 'mindnest-45772.firebaseapp.com',
    storageBucket: 'mindnest-45772.firebasestorage.app',
    measurementId: 'G-36YS5NELY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr4oAp5w2JrIlamW7Ubz_9KExxnBnGX4E',
    appId: '1:853014272041:android:a532377c7615138e6ce438',
    messagingSenderId: '853014272041',
    projectId: 'mindnest-45772',
    storageBucket: 'mindnest-45772.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPT-13wWI1nkhB2beImli0uXwkGIufi1o',
    appId: '1:853014272041:ios:e66c221ab0a84a7a6ce438',
    messagingSenderId: '853014272041',
    projectId: 'mindnest-45772',
    storageBucket: 'mindnest-45772.firebasestorage.app',
    iosClientId:
        '853014272041-efl096jkr75lss9q4jo858pi85sfnjg2.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindnest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPT-13wWI1nkhB2beImli0uXwkGIufi1o',
    appId: '1:853014272041:ios:e66c221ab0a84a7a6ce438',
    messagingSenderId: '853014272041',
    projectId: 'mindnest-45772',
    storageBucket: 'mindnest-45772.firebasestorage.app',
    iosClientId:
        '853014272041-efl096jkr75lss9q4jo858pi85sfnjg2.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindnest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6f1SvmxQljip0KkGeAvbNz2wC9gCThtc',
    appId: '1:853014272041:web:02d41914790c2a056ce438',
    messagingSenderId: '853014272041',
    projectId: 'mindnest-45772',
    authDomain: 'mindnest-45772.firebaseapp.com',
    storageBucket: 'mindnest-45772.firebasestorage.app',
    measurementId: 'G-36YS5NELY5',
  );
}
