// firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcam7IEdnmJnfAYDl6sriE0mXr_IJMBys',
    appId: '1:253632223556:web:4d4d0039f0c223fe56df11',
    messagingSenderId: '253632223556',
    projectId: 'mindnest-923fb',
    authDomain: 'mindnest-923fb.firebaseapp.com',
    storageBucket: 'mindnest-923fb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd2S-KYPs1239bT9-v08A07Dlj_zW8ESc',
    appId: '1:253632223556:android:15dc6e869834b77c56df11',
    messagingSenderId: '253632223556',
    projectId: 'mindnest-923fb',
    storageBucket: 'mindnest-923fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgrFCIYCoPPwF0Nq5oKt3FKbLbj_sIjPk',
    appId: '1:253632223556:ios:1724c954f898a4c856df11',
    messagingSenderId: '253632223556',
    projectId: 'mindnest-923fb',
    storageBucket: 'mindnest-923fb.firebasestorage.app',
    iosBundleId: 'com.example.mindnest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgrFCIYCoPPwF0Nq5oKt3FKbLbj_sIjPk',
    appId: '1:253632223556:ios:1724c954f898a4c856df11',
    messagingSenderId: '253632223556',
    projectId: 'mindnest-923fb',
    storageBucket: 'mindnest-923fb.firebasestorage.app',
    iosBundleId: 'com.example.mindnest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcam7IEdnmJnfAYDl6sriE0mXr_IJMBys',
    appId: '1:253632223556:web:4c051d502101d52756df11',
    messagingSenderId: '253632223556',
    projectId: 'mindnest-923fb',
    authDomain: 'mindnest-923fb.firebaseapp.com',
    storageBucket: 'mindnest-923fb.firebasestorage.app',
  );
}
